services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: blank@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  pgdata:
